server: 
  servlet:
    context-path: /cliente-fiado/api

spring:
  datasource: 
    url: jdbc:mariadb://localhost:3306/cliente-fiado?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driverClassName: org.mariadb.jdbc.Driver

springdoc:
  swagger-ui:
    path:/public/swagger  
