server: 
  servlet:
    context-path: /cliente-fiado/api

spring:
  datasource: 
    url: jdbc:mariadb://localhost:3306/cliente-fiado?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
    
jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /public/swagger 
