server:
  servlet:
    context-path: /cliente-fiado/api 

    
spring.datasource.url=jdbc:mariadb://localhost:3306/cliente-fiado
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop